# Highly divisible triangular number

# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:



tr = 12228490
d = 0
count_divisors = 0
while count_divisors < 500:
    d += 1
    tr += d    
    # Виводить номер трикутного числа, значення трикутного числа
    # print(d,tr) 
    
    count_divisors = 0 
    for i in range(1,tr+1):
        if tr % i == 0:
            count_divisors += 1
    # Виводить число та кількість його дільників
    print(tr,count_divisors)

