# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

x = y = 1
s = 0
for i in range(30):
    if y < 4000000 and y % 2 == 0:
        s += y
    x = x + y
    if x < 4000000 and x % 2==0:
        s += x
    y = x + y
print(s)
    
    


